/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sang2k.app_tracnghiem.User;

import com.sang2k.app_tracnghiem.User.Main;
import com.sang2k.app_tracnghiem.Dao.BoDeDao;
import com.sang2k.app_tracnghiem.entity.CauHoi;
import com.sang2k.app_tracnghiem.entity.BoDe;
import java.util.List;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Yahiko
 */
public class Question extends javax.swing.JPanel {
    public static String choose;
    //int  choose=0;
    int dem=0;
    int diem=0;
    Main main;
    String id;
    /**
     * Creates new form Cauhoi
     */
    public Question(BoDe de) {
        initComponents();
        txt_noidung.setText(de.getNoiDung());
        rdb_a.setText("A. "+de.getA());
        rdb_b.setText("B. "+de.getB());
        rdb_c.setText("C. "+de.getC());
        rdb_d.setText("D. "+de.getD());
        id=de.getCauHoi();
      
    }
    public Question() {
//        initComponents();
//        int id=1 + (int)(Math.random() * ((100 - 1) + 1));
//        dem++;
//        choose=id;
//        try {
//            BoDeDao bd=new BoDeDao();
//            BoDe de=bd.FindBoDe(id);
//            txt_noidung.setText(de.getNoiDung());
//            rdb_a.setText("A. "+de.getA());
//            rdb_b.setText("B. "+de.getB());
//            rdb_c.setText("C. "+de.getC());
//            rdb_d.setText("D. "+de.getD());
//            old.setCh(de.getNoiDung());
//            old.setA(de.getA());
//            old.setB(de.getB());
//            old.setC(de.getC());
//            old.setD(de.getD());
//        } catch (Exception e) {
//        }
//        Getdata();
    }
    public static String Choose()
    {
        return choose;
//            try {
//                try (Socket client = new Socket("localhost" ,9999)) {
//                    DataInputStream DT=new DataInputStream(client.getInputStream());
//                    DataOutputStream OT=new DataOutputStream(client.getOutputStream());
//                    ObjectOutputStream OOS = new ObjectOutputStream(client.getOutputStream()) ;
//                    //ObjectInputStream  IS = new ObjectInputStream(client.getInputStream()) ;
//                    OT.writeInt(1);
//                    OOS.writeObject(SV);
//                    boolean check=DT.readBoolean();
//                    if (check==true) diem=diem+5;
//                }
//            }
//            catch (IOException ex) {
//            }
//            } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_noidung = new javax.swing.JTextArea();
        rdb_a = new javax.swing.JRadioButton();
        rdb_b = new javax.swing.JRadioButton();
        rdb_c = new javax.swing.JRadioButton();
        rdb_d = new javax.swing.JRadioButton();
        btn_next = new javax.swing.JButton();
        btn_nop = new javax.swing.JButton();

        jLabel1.setText("Câu Hỏi");

        txt_noidung.setColumns(20);
        txt_noidung.setRows(5);
        jScrollPane1.setViewportView(txt_noidung);

        group.add(rdb_a);
        rdb_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdb_aMouseClicked(evt);
            }
        });

        group.add(rdb_b);
        rdb_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdb_bMouseClicked(evt);
            }
        });

        group.add(rdb_c);
        rdb_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_cActionPerformed(evt);
            }
        });

        group.add(rdb_d);
        rdb_d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdb_dMouseClicked(evt);
            }
        });

        btn_next.setText("Get KQ");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_nop.setText("Nộp Bài");
        btn_nop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdb_d)
                            .addComponent(rdb_a)
                            .addComponent(rdb_b)
                            .addComponent(rdb_c)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_next)
                .addGap(50, 50, 50)
                .addComponent(btn_nop)
                .addGap(264, 264, 264))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(rdb_a)
                .addGap(36, 36, 36)
                .addComponent(rdb_b)
                .addGap(33, 33, 33)
                .addComponent(rdb_c)
                .addGap(27, 27, 27)
                .addComponent(rdb_d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_next)
                    .addComponent(btn_nop))
                .addGap(134, 134, 134))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nopActionPerformed
        JOptionPane.showMessageDialog(this,"Điểm Của Bạn :"+String.valueOf(diem),"Thông Báo",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_nopActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        if (rdb_a.isSelected()==true) System.out.println("A");
        if (rdb_b.isSelected()==true) System.out.println("B");
        if (rdb_c.isSelected()==true) System.out.println("C");
        if (rdb_d.isSelected()==true) System.out.println("D");
    }//GEN-LAST:event_btn_nextActionPerformed

    private void rdb_aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdb_aMouseClicked
        System.out.println("A");
        System.out.println(id);
        this.choose="A";
//        try {
//                try (Socket client = new Socket("localhost" ,9999)) {
//                    DataInputStream DT=new DataInputStream(client.getInputStream());
//                    DataOutputStream OT=new DataOutputStream(client.getOutputStream());
//                    ObjectOutputStream OOS = new ObjectOutputStream(client.getOutputStream()) ;
//                    //ObjectInputStream  IS = new ObjectInputStream(client.getInputStream()) ;
//                    OT.writeInt(1);
//                    OT.writeBytes(id);
//                    OT.writeBytes("A");
//                    boolean check=DT.readBoolean();
//                    if (check==true) diem=diem+5;
//                }
//            }
//            catch (IOException ex) {
//            }
    }//GEN-LAST:event_rdb_aMouseClicked

    private void rdb_bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdb_bMouseClicked
         System.out.println("B");
         System.out.println(id);
         this.choose="B";
    }//GEN-LAST:event_rdb_bMouseClicked

    private void rdb_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_cActionPerformed
        System.out.println("C");
        System.out.println(id);
        this.choose="C";
    }//GEN-LAST:event_rdb_cActionPerformed

    private void rdb_dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdb_dMouseClicked
        System.out.println("D");
        System.out.println(id);
        this.choose="D";
    }//GEN-LAST:event_rdb_dMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_nop;
    private javax.swing.ButtonGroup group;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdb_a;
    private javax.swing.JRadioButton rdb_b;
    private javax.swing.JRadioButton rdb_c;
    private javax.swing.JRadioButton rdb_d;
    private javax.swing.JTextArea txt_noidung;
    // End of variables declaration//GEN-END:variables
}
